version: '3.9'
#mongoDB services
services:
  mongo_db:
    container_name: backend_db
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

#Nodejs api services
  api:
    container_name: clientcont
    build: .
    ports:
      - 3000:5000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 5000
      mongodb_url: mongodb://mongo_db:27017
      dbName: yolomy
      NAME: Tabbieip2
    depends_on:
     - mongo_db

volumes:
  mongo_db: {}