version: '3.9'
#mongoDB services
services:
  mongo_db:
    container_name: backend_db
    image: mongo:latest
    restart: always
    volumes:
      -mongo_db:/data/db

    ports:
      - "5001:5001"

#Nodejs api services
api:
  container_name: clientcont
  build: .
  ports:
      - 3000:5000
  environment:
     PORT: 5000
     mongodb_url: mongodb://mongo_db:27017
     dbName: yolomy
     NAME: Tabbieip2
  depends_on:
    - mongo_db

volumes:
  mongo_db: {}
