apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  labels:
    app: yolo
    component: back
spec:
  selector:
    matchLabels:
      app: yolo
  replicas: 3
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
        - name: yolo
          image: tabbieke254/yolo-backend:yolo-backend
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-backend
  labels:
    app: yolo
spec:
  selector:
    app: yolo
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      name: http
      
  