apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
  labels:
    app: yolo
    component: front
spec:
  selector:
    matchLabels:
      component: front
      app: yolo
  replicas: 3
  template:
    metadata:
      labels:
        app: yolo
        component: front
    spec:
      containers:
        - name: frontendyolo
          image: tabbieke254/yolo-frontend:yolo-frontend
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: yolo-frontend
spec:
  type: LoadBalancer
  selector:
    app: yolo-frontend
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
      
 